### PR TITLE
Threshold pvalue

### PR DESCRIPTION
**Pull request by gretaabib**
As mentioned in[ Ddf Research Trip Report - 8/11 ](https://docs.google.com/document/d/1aNKDrMjDVV_FlOPRPm3UxPHO5VKM9X9F1WcT8J627Qk/edit?resourcekey=0-UuGS2awOZgRbPepjcH7ttA ) doc, changed the code to meet the following request: "We have a system that detects fraud at a min radius between 500 to 1500 with X precision at Y recall."

Outputs were recorded in [p_values threshold](https://docs.google.com/document/d/1tSEs19ZCpRwV2gwXDya_DWjATizBdp-P9K-DJ93QwAE/edit?resourcekey=0-540T4jyTzg0wC3Hd-4jQIw) doc.

### CODE REVIEW

**Comment by erickzul** [comment]
Hey Greta, I made a copy with some suggested changes.
Mainly, we want to make sure that the p value of the precision and recall match, as well as making sure in the pipeline we give the user the ability to set their p value. PTAL:
https://colab.sandbox.google.com/drive/10pkvfYmoYOyTOD-wLlMos-QxcQgIDbK6?userstoinvite=benwu%40google.com&sharingaction=manageaccess&role=writer

**Review by erickzul — CHANGES_REQUESTED** [review]
Please allow the user to specify their target precision and recall. Also we need to have the same p value reported for the precision and recall. Example: https://colab.sandbox.google.com/drive/10pkvfYmoYOyTOD-wLlMos-QxcQgIDbK6?userstoinvite=benwu%40google.com&sharingaction=manageaccess&role=writer

**Comment by erickzul** [comment]
> 

Per discussion in ML working session, we are keeping a min_radius of 5km per spec (which is the end of the green buffer per go/ddf-isoscape-validation). We don't have an indeterminate band at this time.

https://screenshot.googleplex.com/3brZKhvq6HpUvws

**Comment by gretaabib** [comment]
@erickzul included your adjustments, removed duplicated cell and also parameterized radius variables. FYI - I guess this merge depends on validation_pipeline_plot_isoscape branch.

**Comment by rothn** [comment]
@erickzul I think what I meant was max_radius, not min_radius. I wonder why not model this uniformly over Brazil or at least the Amazon?

**Review by erickzul — CHANGES_REQUESTED** [review]
Please rebase with latest main.

**Review by erickzul — APPROVED** [review]
We have successfully rebased to main in pair programming session.

**Pull request merged**
